"""
scripts/05_active_learning_loop.py

THE CORE BOOTSTRAPPING ENGINE.

This is the primary IP of the project. It implements the active learning loop
that takes unlabeled satellite imagery and progressively labels it using
the model's own uncertainty to guide which images a human should label next.

How it works (the bootstrapping loop):
─────────────────────────────────────
  Iteration 1:
    [Seed Model] → Run on unlabeled images → Find uncertain predictions
    → Human labels ~50 uncertain images → Retrain → Better model

  Iteration 2:
    [Better Model] → Run on remaining unlabeled images → Find new uncertainties
    → Human labels ~50 more images → Retrain → Even better model

  Repeat until performance plateaus.

The key insight: You label FEWER images total than brute-force labeling,
but you get BETTER model performance because you're always labeling
the images that teach the model the most.

This is like studying for an exam by focusing on your weak areas
rather than reviewing what you already know.
"""

import os
import json
import numpy as np
from pathlib import Path
from typing import List, Dict, Tuple
from ultralytics import YOLO
import cv2
from tqdm import tqdm
from dotenv import load_dotenv
import yaml
import shutil
from datetime import datetime

load_dotenv()

# ─── Config ──────────────────────────────────────────────────────────────────
DATA_DIR = Path(os.getenv("DATA_DIR", "./data"))
MODELS_DIR = Path(os.getenv("MODELS_DIR", "./models"))

BOOTSTRAP_CONFIG = {
    "unlabeled_dir": DATA_DIR / "unlabeled",        # Sentinel-2 unlabeled imagery
    "labeled_dir": DATA_DIR / "yolo_format",        # Existing labeled data
    "bootstrap_dir": DATA_DIR / "bootstrapped",     # New labels generated by loop
    "query_budget": 50,                             # Images to label per iteration
    "uncertainty_threshold": 0.3,                   # Confidence below this = uncertain
    "min_confidence": 0.25,                         # Min confidence to count as detection
    "max_iterations": 10,                           # Max bootstrapping iterations
}


class UncertaintySampler:
    """
    Selects the most uncertain images for human labeling.

    Three uncertainty strategies:
    1. Least Confidence: Pick images where best prediction has lowest confidence
    2. Margin Sampling: Pick images where top-2 predictions are closest in confidence
    3. Entropy: Pick images with highest prediction entropy (most uncertain overall)
    """

    def __init__(self, strategy: str = "entropy"):
        assert strategy in ["least_confidence", "margin", "entropy"]
        self.strategy = strategy

    def score_predictions(self, predictions: List[Dict]) -> float:
        """
        Compute uncertainty score for a single image's predictions.
        Higher score = more uncertain = more valuable to label.
        """
        if not predictions:
            # No detections: could be empty image OR missed objects (false negatives)
            # We still want to review these — this is where false negatives hide
            return 0.5  # Medium uncertainty for empty predictions

        confidences = [p["confidence"] for p in predictions]

        if self.strategy == "least_confidence":
            # Uncertain if best prediction isn't confident
            return 1.0 - max(confidences)

        elif self.strategy == "margin":
            # Uncertain if top-2 predictions are close in confidence
            sorted_conf = sorted(confidences, reverse=True)
            if len(sorted_conf) == 1:
                return 1.0 - sorted_conf[0]
            return 1.0 - (sorted_conf[0] - sorted_conf[1])

        elif self.strategy == "entropy":
            # Shannon entropy across confidence scores
            # High entropy = model is "spreading its bets" = uncertain
            conf_array = np.array(confidences)
            conf_array = np.clip(conf_array, 1e-10, 1.0)
            # Normalize to probability distribution
            probs = conf_array / conf_array.sum()
            entropy = -np.sum(probs * np.log(probs + 1e-10))
            # Normalize entropy to [0, 1]
            max_entropy = np.log(len(probs)) if len(probs) > 1 else 1.0
            return entropy / max(max_entropy, 1e-10)

        return 0.0


class BootstrappingLoop:
    """
    Manages the full active learning bootstrapping pipeline.
    """

    def __init__(self, model_path: str, config: dict = BOOTSTRAP_CONFIG):
        self.config = config
        self.model = YOLO(model_path)
        self.sampler = UncertaintySampler(strategy="entropy")
        self.iteration = 0
        self.metrics_history = []

        # Create output directories
        for d in ["unlabeled_dir", "labeled_dir", "bootstrap_dir"]:
            Path(config[d]).mkdir(parents=True, exist_ok=True)

        # Track which images have been labeled
        self.labeled_images = self._load_labeled_registry()

    def _load_labeled_registry(self) -> set:
        """Load set of already-labeled image stems."""
        registry_path = self.config["bootstrap_dir"] / "labeled_registry.json"
        if registry_path.exists():
            with open(registry_path) as f:
                return set(json.load(f))
        return set()

    def _save_labeled_registry(self):
        """Persist labeled image registry."""
        registry_path = self.config["bootstrap_dir"] / "labeled_registry.json"
        with open(registry_path, "w") as f:
            json.dump(list(self.labeled_images), f)

    def run_inference_on_unlabeled(self, images: List[Path]) -> Dict[str, Dict]:
        """
        Run model on unlabeled images and collect predictions with confidence scores.
        """
        results = {}

        for img_path in tqdm(images, desc="Running inference"):
            preds = self.model.predict(
                source=str(img_path),
                conf=self.config["min_confidence"],
                verbose=False
            )[0]

            # Extract predictions
            detections = []
            if preds.boxes is not None:
                for box in preds.boxes:
                    detections.append({
                        "class_id": int(box.cls.item()),
                        "confidence": float(box.conf.item()),
                        "bbox": box.xywhn.tolist()[0],  # normalized xywh
                    })

            uncertainty = self.sampler.score_predictions(detections)

            results[img_path.stem] = {
                "path": str(img_path),
                "predictions": detections,
                "uncertainty": uncertainty,
                "n_detections": len(detections),
            }

        return results

    def select_query_batch(self, inference_results: Dict) -> List[str]:
        """
        Select the most uncertain images to send for human labeling.
        This is the core active learning selection step.
        """
        # Sort by uncertainty (highest first)
        sorted_results = sorted(
            inference_results.items(),
            key=lambda x: x[1]["uncertainty"],
            reverse=True
        )

        # Filter out already-labeled images
        candidates = [
            stem for stem, _ in sorted_results
            if stem not in self.labeled_images
        ]

        # Return top N by budget
        query_batch = candidates[:self.config["query_budget"]]

        print(f"\n📋 Query Batch Statistics:")
        print(f"   Total unlabeled images: {len(inference_results)}")
        print(f"   Already labeled: {len(self.labeled_images)}")
        print(f"   Selected for labeling: {len(query_batch)}")

        if query_batch:
            uncertainties = [inference_results[s]["uncertainty"] for s in query_batch]
            print(f"   Avg uncertainty score: {np.mean(uncertainties):.4f}")
            print(f"   Max uncertainty score: {max(uncertainties):.4f}")

        return query_batch

    def export_query_batch_for_labeling(
        self,
        query_stems: List[str],
        inference_results: Dict
    ) -> Path:
        """
        Export the query batch to a directory for human review.
        Copies images and saves pseudo-labels (model predictions) as starting points.
        Human annotator reviews and corrects these — much faster than labeling from scratch.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        export_dir = self.config["bootstrap_dir"] / f"iteration_{self.iteration:02d}_{timestamp}"
        export_imgs = export_dir / "images"
        export_labels = export_dir / "pseudo_labels"  # Model predictions (to be corrected)
        export_imgs.mkdir(parents=True, exist_ok=True)
        export_labels.mkdir(parents=True, exist_ok=True)

        for stem in query_stems:
            result = inference_results[stem]
            src_path = Path(result["path"])

            # Copy image
            shutil.copy(src_path, export_imgs / src_path.name)

            # Save pseudo-labels (model predictions as starting point for human review)
            label_lines = []
            for pred in result["predictions"]:
                x, y, w, h = pred["bbox"]
                label_lines.append(f"{pred['class_id']} {x:.6f} {y:.6f} {w:.6f} {h:.6f}")

            label_file = export_labels / f"{stem}.txt"
            label_file.write_text("\n".join(label_lines))

        # Save metadata
        metadata = {
            "iteration": self.iteration,
            "timestamp": timestamp,
            "n_images": len(query_stems),
            "stems": query_stems,
            "instructions": (
                "Review pseudo_labels/ directory. "
                "Each .txt file contains model predictions (YOLO format). "
                "Correct any errors, add missing objects, remove false positives. "
                "Then run the import_corrections() function."
            )
        }

        with open(export_dir / "metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)

        print(f"\n📁 Query batch exported to: {export_dir}")
        print(f"   Review and correct labels in: {export_dir}/pseudo_labels/")
        print(f"   Instructions saved to: {export_dir}/metadata.json")

        return export_dir

    def measure_bootstrapping_efficiency(
        self,
        iteration: int,
        n_labeled: int,
        val_metrics: Dict
    ) -> Dict:
        """
        Quantifies how efficiently the bootstrapping process improves the model.

        This is the "efficiency model" required by the original SBIR scope.
        Tracks: labels_used, performance_gain, efficiency_ratio
        """
        metric = {
            "iteration": iteration,
            "cumulative_labels": n_labeled,
            "mAP50": val_metrics.get("metrics/mAP50(B)", 0),
            "mAP50_95": val_metrics.get("metrics/mAP50-95(B)", 0),
            "precision": val_metrics.get("metrics/precision(B)", 0),
            "recall": val_metrics.get("metrics/recall(B)", 0),
        }

        # Efficiency: performance gain per label added
        if len(self.metrics_history) > 0:
            prev = self.metrics_history[-1]
            delta_map = metric["mAP50"] - prev["mAP50"]
            delta_labels = metric["cumulative_labels"] - prev["cumulative_labels"]
            metric["map_gain_per_label"] = delta_map / max(delta_labels, 1)
        else:
            metric["map_gain_per_label"] = 0.0

        self.metrics_history.append(metric)
        self._save_efficiency_report()

        return metric

    def _save_efficiency_report(self):
        """Save bootstrapping efficiency metrics to JSON."""
        report_path = self.config["bootstrap_dir"] / "efficiency_report.json"
        with open(report_path, "w") as f:
            json.dump(self.metrics_history, f, indent=2)
        print(f"📊 Efficiency report updated: {report_path}")

    def run_iteration(self) -> Dict:
        """
        Execute one full iteration of the bootstrapping loop.
        Returns metrics for this iteration.
        """
        self.iteration += 1
        print(f"\n{'='*50}")
        print(f"🔄 BOOTSTRAPPING ITERATION {self.iteration}")
        print(f"{'='*50}")

        # Step 1: Find unlabeled images
        unlabeled_dir = Path(self.config["unlabeled_dir"])
        all_images = list(unlabeled_dir.glob("*.jpg")) + list(unlabeled_dir.glob("*.png"))
        unlabeled = [img for img in all_images if img.stem not in self.labeled_images]

        if not unlabeled:
            print("✅ No more unlabeled images. Bootstrapping complete.")
            return {}

        print(f"\n📷 Found {len(unlabeled)} unlabeled images")

        # Step 2: Run inference and score uncertainty
        inference_results = self.run_inference_on_unlabeled(unlabeled)

        # Step 3: Select query batch (most uncertain images)
        query_batch = self.select_query_batch(inference_results)

        if not query_batch:
            print("✅ All images have been labeled.")
            return {}

        # Step 4: Export for human labeling
        export_dir = self.export_query_batch_for_labeling(query_batch, inference_results)

        # Mark as sent for labeling (will be confirmed when corrections imported)
        self.labeled_images.update(query_batch)
        self._save_labeled_registry()

        print(f"\n⏸️  PAUSE: Human labeling required")
        print(f"   1. Open Roboflow and review/correct labels in: {export_dir}")
        print(f"   2. Export corrected labels back to YOLO format")
        print(f"   3. Run: python scripts/06_retrain_with_bootstrap.py --iteration {self.iteration}")

        result = {
            "iteration": self.iteration,
            "query_batch": query_batch,
            "export_dir": str(export_dir),
            "n_labeled_total": len(self.labeled_images),
        }

        # Save iteration data to Supabase
        try:
            from supabase_storage import SupabaseStorageManager
            manager = SupabaseStorageManager()
            manager.save_bootstrap_iteration({
                "iteration": self.iteration,
                "n_images_labeled": len(query_batch),
                "cumulative_labels": len(self.labeled_images),
            })
            # Also upload bootstrapped labels to Supabase
            export_path = Path(export_dir)
            manager.upload_dataset_batch(
                image_dir=export_path / "images",
                label_dir=export_path / "pseudo_labels",
                split=f"iteration_{self.iteration:02d}",
                prefix="bootstrapped"
            )
        except Exception as e:
            print(f"⚠️  Supabase sync skipped: {e}")

        return result


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Run active learning bootstrapping loop")
    parser.add_argument(
        "--model",
        default=str(MODELS_DIR / "baseline_v1" / "weights" / "best.pt"),
        help="Path to trained model weights"
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=1,
        help="Number of bootstrapping iterations to run"
    )
    args = parser.parse_args()

    if not Path(args.model).exists():
        print(f"❌ Model not found: {args.model}")
        print("   Run scripts/04_train_baseline.py first")
        exit(1)

    loop = BootstrappingLoop(model_path=args.model)

    for i in range(args.iterations):
        result = loop.run_iteration()
        if not result:
            break

    print(f"\n✅ Bootstrapping loop complete. Labeled {len(loop.labeled_images)} images total.")
